---
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'prettier'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  quotes:
    - error
    - single
    - { 'avoidEscape': true, 'allowTemplateLiterals': false }
  no-restricted-syntax: warn
  indent: [warn, 2]
  space-infix-ops: warn
  padded-blocks: warn
  semi: warn


