---
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'prettier'

parserOptions:
  ecmaVersion: latest

plugins:
  - 'fp'

rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  quotes:
    - error
    - single
    - { 'avoidEscape': true, 'allowTemplateLiterals': false }
  no-restricted-syntax: error
  indent: [warn, 2, { SwitchCase: 1 }]
  space-infix-ops: warn
  padded-blocks: warn
  semi: warn
  no-multi-spaces: warn
  max-len: [warn, {code: 100}]
  eol-last: warn
  #  fp/no-arguments: error
#  fp/no-class: error
#  fp/no-delete: error
#  fp/no-events: error
#  fp/no-get-set: error
  fp/no-let: error
  fp/no-loops: error
#  fp/no-mutating-assign: error
  fp/no-mutating-methods: error
  fp/no-mutation: error
#  fp/no-nil: error
#  fp/no-proxy: error
#  fp/no-rest-parameters: error
#  fp/no-this: error
#  fp/no-throw: error
##  fp/no-unused-expression: error
#  fp/no-valueof-field: error
#  no-var: error


